### ISSUE TITLE
Names of the Builder Interfaces

### ISSUE THREAD

**Issue by eddyrokr** [skinny85/jilt#1]
The names of the builder interfaces and the domain classes in the project sometime have the same name. Renaming the builder interfaces differently could avoid confusion while importing the domain classes.

For example, consider an interface UserId. If there is a domain class named UserId, there will be a confusion while importing it since there is an interface with the same name. This could be avoided if the interface is named differently.

**Comment by skinny85** [comment]
Just to expand on what Eddy wrote: currently, the name of the inner Builder interface for each property is simply the (capitalized) name of the property itself. So, if the name of the property is the same as the name of its type (which is a common convention in Java):

```java
package com.example;

import org.jilt.Builder;
import org.jilt.BuilderStyle;

@Builder(style = BuilderStyle.TYPE_SAFE)
class MyDomainClass {
    private final UserId userId;

    // rest of the class ...
}
```

, then you will have two `UserId`s: `com.example.UserId` (the domain class) and `com.example.MyDomainClassBuilders.UserId` (the Builder property interface).

**Comment by skinny85** [comment]
Here's what I'm thinking for a design for this feature:

* An annotation that can be used alongside `@Builder` (working name: `@BuilderInterfaces`. I'm also thinking about `@PropertyClasses`.`@BuilderPropertyClasses` would be more precise, but I'm afraid that one might be too long. Perhaps make it an inner annotation of `@Builder`, so `@Builder.PropertyClasses`?). Its attributes will probably be something like:
  * `outer: String`: the name of the outer interface (optional, the default is the same it is now, `<BuiltClassName>Builders`)
  * `inner: String`: the name pattern used for naming the inner interfaces (the ones for each property). It's a pattern instead of a single name, because you can use `*` in it as the (capitalized) name of the property. So, in the above example with `UserId`, if the value of this attribute would be `"Prop*"`, the name of the interface for `UserId` would be `MyDomainClassBuilders.PropUserId`.
   * (Optional) `packageName`, that allows you to control in what package do the per-property interfaces reside. The default is, like currently, for them to reside in the same package as the Builder class.  It's not strictly required for this particular story, but it might be a nice addition nonetheless, as you can't change it at all now, and it has nice symmetry with the `@Builder.packageName` attribute.
* (Optional) A separate annotation (working name: `@PropertyInterface` / `@PropertyClass`) that can be used on fields and parameters. It has just one attribute, `value: String`, that allows you to set the name of the inner interface for this property to whatever you want. Again, not strictly required, but perhaps worth if if we're allowing customizing the names anyway.

What do you think Eddy? Does this solve the original problem that you had?

**Comment by eddyrokr** [comment]
Hi @skinny85, I like the inner-interface-with-properties idea. Also, the `@PropertyInterface` makes sense. I think these changes would make the library flexible enough to avoid confusion.

**Comment by skinny85** [comment]
Hey Eddy,

I've submitted a Pull Request (#2) with this functionality. You don't have to review every changed line, but let me know if this solves your problem.

The TL;DR is: I added a `@BuilderInterfaces` annotation that has a bunch of properties that let you customize the generated interfaces. Your particular concern is handled by the `innerNames` attribute. So, if we come back to the original example from the beginning of the issue, you can now do the following:

```java
package com.example;

import org.jilt.Builder;
import org.jilt.BuilderInterfaces;
import org.jilt.BuilderStyle;

@Builder(style = BuilderStyle.TYPE_SAFE)
@BuilderInterfaces(innerNames = "J*")
class MyDomainClass {
    private final UserId userId;

    // rest of the class ...
}
```

, and the generated interface for the `userId` property will be `com.example.MyDomainClassBuilders.JUserId`, so it will no longer clash with the `com.example.UserId` domain class.

Let me know if this makes sense!

Thanks,
Adam

**Comment by eddyrokr** [comment]
Sounds great Adam! I will go through the new changes to use the new features. I think this customization option adds value to the library. Thanks a lot!
