### ISSUE TITLE
Support private constructor and nested builder

### ISSUE THREAD

**Issue by murdos** [skinny85/jilt#13]
I just tried to replace some hand-written builder code that I have with `jilt`, and I found that it does not work in my case because the only way to instantiate my object is by using the builder, and thus the constructor is private.

Is this something that could be supported?

**Comment by skinny85** [comment]
Hey @murdos,

thanks a lot for opening the issue. The problem with using private constructors is that it bumps against a fundamental limitation of annotation processors in Java, which is that they can't edit existing classes, only create new ones. Yes, Lombok manages to sidestep that limitation, but it does that by [hacking the annotation processor API](https://notatube.blogspot.com/2010/11/project-lombok-trick-explained.html). I want Jilt to be a good citizen of the annotation processor ecosystem, and not use these kinds of tricks.

Would making the constructor package-private be good enough in this case? This way, assuming you keep the Builder class in the same package as your class, which is the default behavior, the Builder would have access to it, and it would at least prevent classes from outside the package from instantiating it in any other way.

As another point, note that Jilt doesn't do any runtime validation of the properties it passes to your class (are things non-`null`, are collections and strings not empty, are numbers positive, etc.), so your class still needs to make sure all of the invariants it needs hold when creating it. Because of that, making the constructor package-private shouldn't be a huge deal (I hope).

Let me know if this makes sense!

Thanks,
Adam

**Comment by murdos** [comment]
Thanks @skinny85 ! It makes sense :-)
I guess then this issue is mainly about documenting the limitation and describe the workaround.

**Comment by skinny85** [comment]
Awesome, I'm glad 🙂.

I think documenting this limitation makes total sense. The main [ReadMe file](https://github.com/skinny85/jilt/blob/master/Readme.md) is probably the best place to do it.

Any suggestions on the best section to put this info in?

**Comment by skinny85** [comment]
This has been fixed in Jilt release `1.5`.

I'm resolving this issue, please comment if you run into this problem again, and I'll be happy to reopen.
