### ISSUE TITLE
Publish to maven central?

### ISSUE THREAD

**Issue by t-oster** [skinny85/jilt#3]
Hi, I like your library and use it in my lazysql library (https://lazysql.thomas-oster.de).
Since I am about to deploy to maven central, I need all dependencies there, too.
Since you're already on jcenter, it should not be too hard to also publish to maven central.

Could you do me that favor?

**Comment by skinny85** [comment]
Hey Thomas,

thanks, that's awesome to know that you're using Jilt!

Do you have any info on how to easily move from JCenter to Maven Central? I'm asking, as I've never done this before, so any pointers would be great.

Thanks,
Adam

**Comment by t-oster** [comment]
Hi. The first and hardest step is to claim your group ID. You have to create an account at sonatype jira https://issues.sonatype.org/secure/Signup!default.jspa and create an issue like this https://issues.sonatype.org/browse/OSSRH-24465.
They will then verify that you own the domain corresponding to your group ID. After that it's just making sure you have a few fields set in your pom and attaching javadoc and gpg signing, but that's not so hard.

You are using `org.jilt` but you do not own the domain `jilt.org`, so your group ID should be `com.github.skinny85`. I am not sure if the java package has to meet the group ID but I don't think so.

The good thing is, that if you successfully deploy to maven central, your artifacts will be synchronized to jcenter, because they mirror maven central.

**Comment by skinny85** [comment]
Thanks for the info.

> You are using org.jilt but you do not own the domain jilt.org, so your group ID should be com.github.skinny85. I am not sure if the java package has to meet the group ID but I don't think so.

Just to clarify: right now, Jilt is distributed under the group ID `org.jilt`. I want to leave it that way. Are you saying that's possible, or will I need to switch to the `com.github.skinny85` group ID for Jilt to be able to publish to Maven Central?

**Comment by t-oster** [comment]
I am not 100% sure, but I think you have to own the domain corresponding to your group ID, so if you do not buy the domain jilt.org, you would have to change the group ID (not necissarily the java package though).

**Comment by skinny85** [comment]
> not necissarily the java package though).

What do you mean by "Java package"? Do you mean the artifact ID?

**Comment by t-oster** [comment]
well I think your java classes can still be like `org.jilt.SomeJavaClass` but the maven/gradle group ID of your artifact would be like
```xml
<dependencies>
    <dependency>
        <groupId>com.github.skinny85</groupId>
        <artifactId>jilt</artifactId>
        <version>1.1</version>
        <scope>provided</scope>
    </dependency>
</dependencies>

**Comment by skinny85** [comment]
Created issue in Sonatype's Jira: https://issues.sonatype.org/browse/OSSRH-52844

**Comment by t-oster** [comment]
Thanks for your effort.

**Comment by skinny85** [comment]
Hey @t-oster,

unfortunately, I was not able to come to an agreement with the current owners of jilt.org, and I really don't want to publish the artifacts under a different group ID :(.

May I suggest a different approach? What if, instead of taking a dependency on Jilt, you were to shade the Jilt JAR into your project's JAR? It's actually a best practice for annotation processor dependencies, because you prevent potential version conflicts if the user of your project happens to also depend on a different version of the same annotation processor as you do (I don't think Jilt is popular enough, or has enough versions, for that to be very likely right now, but you never know...). This way, it wouldn't matter that Jilt is not on Maven Central - your library would be completely in control of the distribution process.

If you want to see an example, that's actually exactly what Jilt does today: it shades in the dependency it has on Square's JavaPoet library. Take a look in the [build.gradle of Jilt](https://github.com/skinny85/jilt/blob/master/build.gradle) for details (the `shadowJar` task).

Let me know if this is an option for you!

Thanks,
Adam

**Comment by t-oster** [comment]
Hi, thanks for all your effort.  So it's okay for you if I include your source tree in mine with changed package name to avoid conflicts? I would keep the copyright header intact.

**Comment by skinny85** [comment]
If you'll use shading, like Jilt does, then you'll be including the compiled bytecode into your JAR, not the source code :)

**Comment by t-oster** [comment]
Have to check if this is possible with maven

**Comment by skinny85** [comment]
> Have to check if this is possible with maven

I'm certain it is.

**Comment by t-oster** [comment]
Well for the Maven shade plugin I would need to have the bytecode available as dependency which is the problem in the first place. Even if I add the compiled jar to my source tree I don't see the way how to reference this with the shade plugin. But is there anything which prevents me from just copying the source tree into mine?

**Comment by skinny85** [comment]
Just add JCenter into your `<repository>` section...? See here: https://github.com/skinny85/jilt#getting-jilt

**Comment by t-oster** [comment]
That's what I already do (see https://lazysql.thomas-oster.de/#installation), but then again I have a dependency to a non-maven-central jar, which is discuraged (see https://maven.apache.org/repository/guide-central-repository-upload.html FAQ).

**Comment by skinny85** [comment]
Right, but this will be a `provided` dependency because of shading, so your consumers will not get it transitively.

**Comment by t-oster** [comment]
Ahh ok, that's the important info I was looking for. Thanks
