### ISSUE TITLE
Migrate artifact repository away from JCenter

### ISSUE THREAD

**Issue by blairnangle** [skinny85/jilt#4]
According to IntelliJ (see screenshot) and [this press release](https://blog.gradle.org/jcenter-shutdown), JCenter is shutting down, so jilt JARs will no longer be fetchable from 2022-02-01.

<img width="795" alt="Screenshot 2021-11-16 at 14 05 09" src="https://user-images.githubusercontent.com/8478158/142000019-800e70a1-e2cf-4d45-9d27-49eb22917c5b.png">

**Comment by blairnangle** [comment]
I am happy to help with the migration, although I imagine project ownership/admin privileges may be required to make such a migration.

**Comment by skinny85** [comment]
Thanks for opening the issue @blairnangle! You are absolutely right that this needs to be done. I'm right now working on moving my other side-project that's hosted on JCenter (https://github.com/skinny85/specnaz) to Maven Central - when I finish that, Jilt will be next 🙂.

Thanks,
Adam

**Comment by blairnangle** [comment]
No worries! Thank you for getting back to me. Let me know if you want any assistance.

**Comment by skinny85** [comment]
Specnaz is [now done](https://github.com/skinny85/specnaz/issues/16#issuecomment-974758629), I will start working on Jilt very soon - we'll make it before February 2022 for sure 🙂.

**Comment by skinny85** [comment]
OK, the library has been [released to Maven Central](https://search.maven.org/artifact/cc.jilt/jilt/1.1/jar)!

**Important note**: the `groupid` of the module has changed. In Maven Central, you need to control the domain that corresponds to the `groupId`, and jilt.org has been bought by domain squatters, I guess because jilt.com was a company website. So, I bought jilt.cc, which was the closest Jilt-related domain that was still available. So, when switching to the dependency from Maven Central, make sure to specify the `groupId` as `cc.jilt`.

However, the Java package name is still `org.jilt`, so after changing the dependency declaration in your `pom.xml` / `build.gradle` file, no changes to your code will be needed.

I'm resolving this one, let me know if run into any problems!

**Comment by blairnangle** [comment]
Awesome. Nice one, @skinny85!
